### ISSUE TITLE
May be add link to role in galaxy https://galaxy.ansible.com/buluma/gitlab ?

### ISSUE THREAD

**Issue by patsevanton** [buluma/ansible-role-gitlab#13]
May be add link to role in galaxy https://galaxy.ansible.com/buluma/gitlab ?

**Comment by buluma** [comment]
100%, new release coming after CI build

**Comment by buluma** [comment]
version [1.0.6](https://github.com/buluma/ansible-role-gitlab/tree/1.0.6) is available on galaxy https://galaxy.ansible.com/buluma/gitlab. let me know if you're sorted when you can

**Comment by patsevanton** [comment]
May be add link https://galaxy.ansible.com/buluma/gitlab to About ?

**Comment by buluma** [comment]
version [1.0.7](https://github.com/buluma/ansible-role-gitlab/releases/tag/1.0.7) is available on galaxy https://galaxy.ansible.com/buluma/gitlab.

**Comment by patsevanton** [comment]
May be add link to role to about ?
![image](https://user-images.githubusercontent.com/10828883/159695498-af58ec83-3d36-44db-ac82-50b12bc69b65.png)

**Comment by buluma** [comment]
done 
<img width="331" alt="image" src="https://user-images.githubusercontent.com/1452922/159709026-e748b4cc-8c3a-4638-b316-f2b66a225ddb.png">
