### ISSUE TITLE
backup_upload_connection doesn`t support endpoint

### ISSUE THREAD

**Issue by patsevanton** [buluma/ansible-role-gitlab#16]
Thanks for role gitlab
I try backup to Digital Ocean Spaces S3 

https://docs.gitlab.com/ee/raketasks/backup_restore.html#digital-ocean-spaces

But gitlab_rails_backup_upload_connection don`t have endpoint

**Comment by patsevanton** [comment]
I am sorry. I search in readme.md

May be rollback https://github.com/buluma/ansible-role-gitlab/commit/457174a47dde87090098f444d7aac0839c4b7d7d
and simple add endpoint to readme.

Changed comment.

**Comment by patsevanton** [comment]
Hm. it is strange. readme contain gitlab_rails_backup_upload_connection. I think need close this issue.

**Comment by buluma** [comment]
yes, I noticed that in testing 818d97ccbc225c7755b70e6f5245dadfc02b64ff. release coming up shortly

**Comment by buluma** [comment]
1.0.8 is available for testing
