### ISSUE TITLE
[Feature request] Extract Password from variable initial_root_password

### ISSUE THREAD

**Issue by patsevanton** [buluma/ansible-role-gitlab#20]
Thanks for role gitlab.
May be add view gitlab password from /etc/gitlab/initial_root_password to role?

My playbook for install gitlab
```
- hosts: gitlab
  become: yes
  roles:
    - role: buluma.gitlab
  post_tasks:
    - name: Read initial_root_password file
      slurp:
        src: /etc/gitlab/initial_root_password
      register: initial_root_password

    - name: Extract Password from variable initial_root_password
      set_fact:
        gitlab_password: "{{ initial_root_password['content'] | b64decode | regex_search('Password: (.+)', '\\1') | first }}"

    - name: Print gitlab password
      debug:
        var: gitlab_password
```

**Comment by patsevanton** [comment]
May add variable 'show gitlab password' and set variable to false.

**Comment by buluma** [comment]
https://github.com/buluma/ansible-role-gitlab/pull/21#pullrequestreview-922471861

**Comment by buluma** [comment]
hey @patsevanton when you can mind giving me a nomination? @buluma https://stars.github.com/nominate/

**Comment by buluma** [comment]
default password would be password, obviously change it immediately. [1.0.15](https://galaxy.ansible.com/buluma/gitlab)
